"""Private object storage for report media, with a local development adapter."""

from __future__ import annotations

import logging
import os
import uuid
from pathlib import Path
from typing import BinaryIO

from app.config import settings

logger = logging.getLogger(__name__)


def _s3_client():
    try:
        import boto3
        from botocore.config import Config
    except ImportError as exc:  # pragma: no cover - deployment configuration
        raise RuntimeError("S3 media storage requires boto3") from exc

    return boto3.client(
        "s3",
        region_name=settings.media_s3_region or None,
        endpoint_url=settings.media_s3_endpoint_url or None,
        aws_access_key_id=settings.media_s3_access_key_id or None,
        aws_secret_access_key=settings.media_s3_secret_access_key or None,
        aws_session_token=settings.media_s3_session_token or None,
        config=Config(s3={"addressing_style": settings.media_s3_addressing_style}),
    )


def _local_path(key: str) -> Path:
    # Keys are generated by this module; still reject traversal defensively.
    if not key or Path(key).is_absolute() or ".." in Path(key).parts:
        raise ValueError("Invalid media storage key")
    return Path(settings.media_storage_path).resolve() / key


def new_storage_key() -> str:
    return f"reports/{uuid.uuid4().hex}"


def put_object(key: str, data: bytes, content_type: str) -> None:
    if settings.media_storage_backend == "s3":
        args = {"Bucket": settings.media_s3_bucket, "Key": key, "Body": data, "ContentType": content_type}
        if settings.media_s3_sse:
            args["ServerSideEncryption"] = settings.media_s3_sse
        if settings.media_s3_kms_key_id:
            args["SSEKMSKeyId"] = settings.media_s3_kms_key_id
        _s3_client().put_object(**args)
        return

    path = _local_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        with temporary.open("xb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def get_object(key: str, backend: str | None = None) -> bytes:
    backend = backend or settings.media_storage_backend
    if backend == "s3":
        response = _s3_client().get_object(Bucket=settings.media_s3_bucket, Key=key)
        body: BinaryIO = response["Body"]
        try:
            return body.read()
        finally:
            body.close()
    return _local_path(key).read_bytes()


def delete_object(key: str, backend: str | None = None) -> None:
    backend = backend or settings.media_storage_backend
    if backend == "s3":
        # S3 delete is idempotent, which makes the retry queue safe.
        _s3_client().delete_object(Bucket=settings.media_s3_bucket, Key=key)
        return
    _local_path(key).unlink(missing_ok=True)

