"""
Schemas Package
Pydantic models for request/response validation
"""

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    UtilityBase,
    UtilityCreate,
    UtilityUpdate,
    UtilityResponse,
    UtilityListResponse,
    UtilityServiceAreaCreate,
    UtilityServiceAreaResponse,
    UtilityManagerBase,
    UtilityManagerCreate,
    UtilityManagerResponse,
    UtilityManagerListResponse,
    DMABase,
    DMACreate,
    DMAUpdate,
    DMAResponse,
    DMAListResponse,
    DMAManagerBase,
    DMAManagerCreate,
    DMAManagerResponse,
    DMAManagerListResponse,
    TeamBase,
    TeamCreate,
    TeamUpdate,
    TeamResponse,
    TeamListResponse,
    EngineerBase,
    EngineerCreate,
    EngineerUpdate,
    EngineerResponse,
    EngineerListResponse,
)

from app.schemas.business import (
    ReportBase,
    ReportCreate,
    ReportUpdate,
    ReportResponse,
    ReportListResponse,
    ReportStatusUpdateRequest,
    ActivityLogBase,
    ActivityLogCreate,
    ActivityLogResponse,
    ActivityLogListResponse,
    ActivityLogFilterRequest,
    NotificationBase,
    NotificationCreate,
    NotificationUpdate,
    NotificationResponse,
    NotificationListResponse,
    NotificationBulkCreate,
    PushTokenRegisterRequest,
    PushTokenResponse,
)

from app.schemas.sensors import (
    TankCreate,
    TankPatch,
    TankRead,
    TankListResponse,
    TankSyncSummary,
    SensorRegisterRequest,
    SensorRegisterResponse,
    SensorUpdateRequest,
    SensorIngestRequest,
    SensorIngestResponse,
    SensorRead,
    SensorListResponse,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    # Utility schemas
    "UtilityBase",
    "UtilityCreate",
    "UtilityUpdate",
    "UtilityResponse",
    "UtilityListResponse",
    "UtilityServiceAreaCreate",
    "UtilityServiceAreaResponse",
    # Utility Manager schemas
    "UtilityManagerBase",
    "UtilityManagerCreate",
    "UtilityManagerResponse",
    "UtilityManagerListResponse",
    # DMA schemas
    "DMABase",
    "DMACreate",
    "DMAUpdate",
    "DMAResponse",
    "DMAListResponse",
    # DMA Manager schemas
    "DMAManagerBase",
    "DMAManagerCreate",
    "DMAManagerResponse",
    "DMAManagerListResponse",
    # Team schemas
    "TeamBase",
    "TeamCreate",
    "TeamUpdate",
    "TeamResponse",
    "TeamListResponse",
    # Engineer schemas
    "EngineerBase",
    "EngineerCreate",
    "EngineerUpdate",
    "EngineerResponse",
    "EngineerListResponse",
    # Report schemas
    "ReportBase",
    "ReportCreate",
    "ReportUpdate",
    "ReportResponse",
    "ReportListResponse",
    "ReportStatusUpdateRequest",
    # Activity Log schemas
    "ActivityLogBase",
    "ActivityLogCreate",
    "ActivityLogResponse",
    "ActivityLogListResponse",
    "ActivityLogFilterRequest",
    # Notification schemas
    "NotificationBase",
    "NotificationCreate",
    "NotificationUpdate",
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationBulkCreate",
    "PushTokenRegisterRequest",
    "PushTokenResponse",
    # Tank schemas
    "TankCreate",
    "TankPatch",
    "TankRead",
    "TankListResponse",
    "TankSyncSummary",
    # Sensor schemas
    "SensorRegisterRequest",
    "SensorRegisterResponse",
    "SensorUpdateRequest",
    "SensorIngestRequest",
    "SensorIngestResponse",
    "SensorRead",
    "SensorListResponse",
]
